#!/bin/bash

# Lock-In Responsible - Development Quick Start Script
# This script starts everything you need for local development

set -e  # Exit on error

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Lock-In Responsible - Development Setup${NC}"
echo ""

# Check if dfx is installed
if ! command -v dfx &> /dev/null; then
    echo -e "${RED}❌ DFX SDK not found${NC}"
    echo -e "${YELLOW}Install it with: sh -ci \"\$(curl -fsSL https://internetcomputer.org/install.sh)\"${NC}"
    exit 1
fi

echo -e "${GREEN}✓ DFX SDK found${NC}"

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js not found${NC}"
    echo -e "${YELLOW}Install it from: https://nodejs.org${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Node.js found ($(node --version))${NC}"
echo ""

# Step 1: Start local ICP network
echo -e "${BLUE}📡 Starting local ICP network...${NC}"
dfx start --clean --background

# Wait for dfx to be ready
sleep 3

if dfx ping &> /dev/null; then
    echo -e "${GREEN}✓ Local ICP network running${NC}"
else
    echo -e "${RED}❌ Failed to start local network${NC}"
    exit 1
fi

echo ""

# Step 2: Deploy canister
echo -e "${BLUE}🚢 Deploying canister to local network...${NC}"
dfx deploy lock_in_backend

CANISTER_ID=$(dfx canister id lock_in_backend)
echo -e "${GREEN}✓ Canister deployed${NC}"
echo -e "${YELLOW}   Canister ID: $CANISTER_ID${NC}"
echo ""

# Step 3: Update frontend configuration
echo -e "${BLUE}⚙️  Updating frontend configuration...${NC}"
cat > frontend/.env << EOF
# ICP Canister Configuration (Auto-generated by start-dev.sh)
VITE_ICP_CANISTER_ID=$CANISTER_ID
VITE_ICP_NETWORK=development
VITE_APP_NAME="Lock-In Responsible"
EOF

echo -e "${GREEN}✓ Frontend .env updated${NC}"
echo ""

# Step 4: Install frontend dependencies if needed
if [ ! -d "frontend/node_modules" ]; then
    echo -e "${BLUE}📦 Installing frontend dependencies...${NC}"
    cd frontend && npm install && cd ..
    echo -e "${GREEN}✓ Dependencies installed${NC}"
    echo ""
else
    echo -e "${GREEN}✓ Frontend dependencies already installed${NC}"
    echo ""
fi

# Done!
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ DEVELOPMENT ENVIRONMENT READY!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}🌐 Next steps:${NC}"
echo -e "   1. Open a new terminal"
echo -e "   2. Run: ${YELLOW}cd frontend && npm run dev${NC}"
echo -e "   3. Open: ${YELLOW}http://localhost:5173${NC}"
echo -e "   4. Click 'Login with Internet Identity'"
echo ""
echo -e "${BLUE}📝 Useful commands:${NC}"
echo -e "   • ${YELLOW}dfx stop${NC}                 - Stop local network"
echo -e "   • ${YELLOW}dfx canister logs lock_in_backend${NC} - View logs"
echo -e "   • ${YELLOW}dfx deploy lock_in_backend${NC} - Redeploy after changes"
echo ""
echo -e "${BLUE}💡 Tip:${NC} Keep the ICP network running in the background"
echo -e "         To stop: ${YELLOW}dfx stop${NC}"
echo ""
